"""Add books and authors relationship

Revision ID: a16829099dc1
Revises: 
Create Date: 2024-05-06 18:58:01.637891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16829099dc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('birthDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('birthDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BookAuthor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookId', sa.Integer(), nullable=True),
    sa.Column('authorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authorId'], ['Author.id'], ),
    sa.ForeignKeyConstraint(['bookId'], ['Book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BookAuthor')
    op.drop_table('Book')
    op.drop_table('Author')
    # ### end Alembic commands ###
